app/home/forms.py
# coding:utf8
from flask_wtf import FlaskForm

from wtforms import StringField, PasswordField, SubmitField, FileField, TextAreaField, SelectField
from wtforms.validators import DataRequired, ValidationError


class RegisteForm(FlaskForm):
    nickname = StringField(
        label="昵称",
        validators=[
            DataRequired("请输入昵称！")
        ],
        description="昵称",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "昵称",
            "id": "input_name",

        }

    )
    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("请输入邮箱！")
        ],
        description="邮箱",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "邮箱",
            "id": "input_email",

        }

    )
    phone = StringField(
        label="手机",
        validators=[
            DataRequired("请输入手机！")
        ],
        description="手机",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "手机",
            "id": "input_phone",

        }

    )
    password = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码！")
        ],
        description="密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "密码",
            "id": "input_password",

        }

    )
    repassword = PasswordField(
        label="确认密码",
        validators=[
            DataRequired("请输入确认密码！")
        ],
        description="确认密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "确认密码",
            "id": "input_repassword",

        }

    )
    register = SubmitField(
        '注册',
        render_kw={
            "class": "btn btn-lg btn-success btn-block",

        }
    )


class LoginForm(FlaskForm):
    password = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码")
        ],
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "密码",
            "id": "input_password"
        }
    )
    username = StringField(
        label="账号",
        validators=[
            DataRequired("请输入账号")
        ],
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "用户名",
            "id": "input_contact"
        }
    )
    login = SubmitField(
        '登录',
        render_kw={
            "class": "btn btn-lg btn-success btn-block",

        }
    )


class UserForm(FlaskForm):
    username = StringField(
        label="昵称",
        render_kw={
            "class": "form-control",
            "id": "input_name",
            "placeholder": "昵称",
        }
    )
    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("请输入邮箱！")
        ],
        description="邮箱",
        render_kw={
            "class": "form-control",
            "placeholder": "邮箱",
            "id": "input_email",

        }

    )
    phone = StringField(
        label="手机",
        validators=[
            DataRequired("请输入手机！")
        ],
        description="手机",
        render_kw={
            "class": "form-control",
            "placeholder": "手机",
            "id": "input_phone",

        }

    )
    info = TextAreaField(
        label="简介",
        validators=[
            DataRequired("请输入简介")
        ],
        description="简介",
        render_kw={
            "class": "form-control",
            "rows": 10
        }
    )
    face = FileField(
        label="头像",
        validators=[
            DataRequired("请上传头像")
        ],
        description="头像",
    )
    submit = SubmitField(
        '保存修改',
        render_kw={
            "class": "btn btn-success",

        }
    )
class CommentForm(FlaskForm):
    comment = TextAreaField(
        label='内容',
        validators=[
            DataRequired("请输入评论内容")
        ],
        description="内容",
        render_kw={
            "id":"input_content"
        }

    )
    submit = SubmitField(
        '提交评论',
        render_kw={
            "class": "btn btn-success",
            "id": "btn-sub"

        }
    )
class Pwd_editForm(FlaskForm):
    old_password = PasswordField(
        label="旧密码",
        validators=[
            DataRequired("请输入旧密码")
        ],
        render_kw={
            "class": "form-control",
            "placeholder": "旧密码",
            "id": "input_oldpwd"
        }
    )
    new_password = PasswordField(
        label="新密码",
        validators=[
            DataRequired("请输入新密码")
        ],
        render_kw={
            "class": "form-control",
            "placeholder": "新密码",
            "id": "input_newpwd"
        }
    )
    submit = SubmitField(
        '修改密码',
        render_kw={
            "class": "btn btn-success",


        }
    )
class SearchForm(FlaskForm):
    search = StringField(
        label="搜索",
        validators=[
            DataRequired("请输入内容！")
        ],
        description="内容",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入电影名！",

        }

    )
    submit = SubmitField(
        '搜索',
        render_kw={
            "class": "btn btn-default",

        }
    )

app/home/__init__.py
from flask import Blueprint
home = Blueprint("home",__name__)
import app.home.views

app/home/views.py
import datetime
import os
import uuid
import requests, json, random

from functools import wraps

from werkzeug.utils import secure_filename

from app import db, app
from app.home.forms import RegisteForm, LoginForm, UserForm, CommentForm, Pwd_editForm, SearchForm
from app.models import User, Movie, Comment, Num
from . import home
from werkzeug.security import generate_password_hash, check_password_hash

from flask import render_template, redirect, url_for, flash, request, session


def checkpwd(pwd1, pwd2):
    return check_password_hash(pwd1, pwd2)


# 修改文件名称
def change_filename(filename):
    fileinfo = os.path.splitext(filename)
    filename = datetime.datetime.now().strftime("%Y%m%d%H%%M%S") + str(uuid.uuid4().hex) + fileinfo[-1]
    return filename


def home_login_req(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if "home" not in session:
            return redirect(url_for("home.login", next=request.url))
        return f(*args, **kwargs)

    return decorated_function


def home_login_req2(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if "home" in session:
            return redirect(url_for("home.user", next=request.url))
        return f(*args, **kwargs)

    return decorated_function


@home.route("/login/", methods=['get', 'post'])
@home_login_req2
def login():
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        username = data["username"]
        password = data["password"]
        pwd = User.query.filter_by(name=username).first()
        num = User.query.filter_by(name=username).count()
        if num == 1:
            if checkpwd(pwd.pwd, password):
                session["home"] = username
                print(password)
                return redirect(request.args.get('next', url_for('home.user')))
            else:
                flash("账号或密码错误", "err")
        else:
            flash("账号或密码错误", "err")
            return redirect(url_for("home.login"))

    return render_template("home/login.html", form=form)


@home.route("/logout/")
def logout():
    session.pop("home", None)
    return redirect(url_for("home.login"))


@home.route("/register/", methods=['post', 'get'])
def register():
    form = RegisteForm()
    if form.validate_on_submit():
        data = form.data
        nickname = data["nickname"]
        email = data["email"]
        phone = data["phone"]
        password = data["password"]
        repassword = data["repassword"]
        if password == repassword:
            namenum = User.query.filter_by(name=nickname).count()
            emailnum = User.query.filter_by(email=email).count()
            phonenum = User.query.filter_by(phone=phone).count()
            if namenum == 1:
                flash("用户已经存在！", "err")
            elif emailnum == 1:
                flash("邮箱已经存在", "err")
            elif phonenum == 1:
                flash("手机已经存在", "err")
            else:
                password = generate_password_hash(password)
                user = User(
                    name=nickname,
                    email=email,
                    phone=phone,
                    pwd=password,
                    face='lyj.jpg'
                )
                db.session.add(user)
                db.session.commit()
                flash("注册成功！", "ok")
                redirect(url_for("home.user"))
        else:
            flash("两次密码不一致", "err")
    return render_template("home/register.html", form=form)


@home.route("/user/", methods=['post', 'get'])
@home_login_req
def user():
    form = UserForm()
    name = session["home"]
    userx = User.query.filter_by(name=name).first()
    print(userx.info)
    if form.validate_on_submit():
        data = form.data
        user_count = User.query.filter_by(name=data['username']).count()
        if name == data['username']:
            user_count = user_count - 1
        if user_count == 1:
            flash("昵称已经存在", "err")
        else:
            face = request.files.get('face')
            face.filename = secure_filename(face.filename)
            if not os.path.exists(app.config["UP_DIR"]):
                os.makedirs(app.config["UP_DIR"])
                os.chmod(app.config["UP_DIR"], "rw")
            face_name = change_filename(face.filename)
            face.save(app.config["UP_DIR"] + face_name)
            userx.name = data['username']
            userx.email = data['email']
            userx.phone = data['phone']
            userx.info = data['info']
            userx.face = face_name
            db.session.add(userx)
            db.session.commit()
            session['home'] = data['username']
            flash("保存成功", "ok")
    return render_template("home/user.html", userx=userx, form=form)


@home.route("/pwd/", methods=['post', 'get'])
@home_login_req
def pwd():
    form = Pwd_editForm()
    if form.validate_on_submit():
        data = form.data
        old_pwd1 = data['old_password']
        user = User.query.filter_by(name=session['home']).first()
        new_pwd = data['new_password']
        print(new_pwd)
        if checkpwd(user.pwd, old_pwd1):
            new_pwd = generate_password_hash(new_pwd)
            user.pwd = new_pwd
            db.session.add(user)
            db.session.commit()
            flash("操作成功", 'ok')
        else:
            flash("密码输入错误", 'err')
    return render_template("home/pwd.html", form=form)


@home.route("/comments/<int:page>/")
@home_login_req
def comments(page=None):
    user_id = User.query.filter_by(name=session['home']).first().id
    if page is None:
        page = 1
    page_data = Comment.query.filter_by(user_id=user_id).order_by(Comment.addtime.desc()).paginate(page=page,
                                                                                                   per_page=5)
    return render_template("home/comments.html", page_data=page_data)


@home.route("/")
def index():
    movie = Movie.query.all()
    num = Num.query.first()
    num.num = num.num + 1
    db.session.add(num)
    db.session.commit()

    return render_template("home/index.html", movie=movie, x="已被访问" + str(num.num) + "次")


@home.route("/search/", methods=['post', 'get'])
def search():
    data = request.form.get('search')
    print(data)
    if data is not None:
        moviex = Movie.query.filter(Movie.title.like("%" + data + "%") if data is not None else "").all()
        moviecount = Movie.query.filter(Movie.title.like("%" + data + "%") if data is not None else "").count()
        return render_template("home/search.html", moviex=moviex, data=data, moviecount=moviecount)
    return redirect('/')


@home.route("/play/<int:id>", methods=['get', 'post'])
@home_login_req
def play(id=None):
    form = CommentForm()
    movie = Movie.query.filter_by(id=id).first()
    user = User.query.filter_by(name=session["home"]).first()
    comments = Comment.query.filter_by(movie_id=id).all()
    commentsnum = Comment.query.filter_by(movie_id=id).count()
    if request.method == "POST":
        if form.validate_on_submit():
            data = form.data
            comment = Comment(
                content=data['comment'],
                movie_id=id,
                user_id=user.id,
            )
            db.session.add(comment)
            db.session.commit()
            return redirect("/play/" + str(movie.id))
    return render_template("home/play.html", movie=movie, form=form, comments=comments, commentsnum=commentsnum,
                           user=user)


@home.route('/mycb')
def mycb():
    data = request.args.to_dict()
    code = data.get('code')
    url = 'https://graph.qq.com/oauth2.0/token'
    body = {'grant_type': 'authorization_code', 'client_id': '101860781',
            'client_secret': '0f5a014e13e7d35fbcca51ecc2ff6745', 'code': code, 'redirect_uri': 'https://yujl.top/mycb'}
    response = requests.get(url, params=body)
    token = response.text
    token_url = '?' + token
    requests.session().close()
    return redirect('/token' + token_url)


@home.route('/token')
def token():
    data = request.args.to_dict()
    open_id = get_openid(data)
    user_info = get_user_info(data, open_id)
    uuid_count = User.query.filter_by(uuid=open_id).count()
    if uuid_count == 1:
        name = User.query.filter_by(uuid=open_id).first()
        session['home'] = name.name
        return redirect('/user')
    else:
        password = generate_password_hash('123456')
        hash_name = str(hash(random.randint(1000,9999)))
        name = user_info.get('nickname') + hash_name
        user = User(
            name=name,
            uuid=open_id,
            pwd = password,
            face=user_info.get('figureurl_1')
        )
        db.session.add(user)
        db.session.commit()
        session['home'] = name
        return redirect('/user')





def get_openid(data):
    url = 'https://graph.qq.com/oauth2.0/me'
    body = {'access_token': data.get('access_token')}
    response = requests.get(url, params=body)
    open_id = json.loads(response.text[10:-4])
    open_id = open_id.get('openid')
    requests.session().close()
    return open_id


def get_user_info(data, open_id):
    url = 'https://graph.qq.com/user/get_user_info'
    body = {'access_token': data.get('access_token'), 'oauth_consumer_key': '101860781', 'openid': open_id}
    response1 = requests.get(url, params=body)
    user_info = response1.json()
    requests.session().close()
    return user_info


@home.errorhandler(404)
def page_not_found(error):
    return render_template("home/404.html"), 404

app/templates/home/home.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微视频</title>
    <link rel="shortcut icon" href="{{ url_for('static',filename = 'base/images/logo.png')}}">
    <link rel="stylesheet" href="{{ url_for('static',filename = 'base/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{ url_for('static',filename = 'base/css/bootstrap-movie.css')}}">
    <link rel="stylesheet" href="{{ url_for('static',filename = 'base/css/animate.css')}}">
    <style>
        .navbar-brand>img {
            display: inline;
        }
        .media{
            padding:3px;
            border:1px solid #ccc
        }

    </style>
    {% block css %} {%endblock%}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{url_for('home.index')}}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static',filename = 'base/images/logo.png')}}" style="height:30px;">&nbsp;微视频
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" action="{{url_for('home.search')}}"  method="post" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！" name="search">
                    <span class="input-group-btn">
                        <input type="submit" class="btn btn-default" value="搜索">
<!--                        <a class="btn btn-default" href="{{url_for('home.search')}}"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>-->
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{url_for('home.index')}}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.login')}}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.register')}}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.logout')}}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.user')}}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
<div class="container" style="margin-top:76px">

    {% block content %} {% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2019 liuYuJiang 蜀ICP备19041750号 {{x}}
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static',filename = 'base/js/jquery.min.js')}}"></script>
<script src="{{ url_for('static',filename = 'base/js/bootstrap.min.js')}}"></script>
<script src="{{ url_for('static',filename = 'base/js/jquery.singlePageNav.min.js')}}"></script>
<script src="{{ url_for('static',filename = 'base/js/wow.min.js')}}"></script>
<script src="{{ url_for('static',filename = 'lazyload/jquery.lazyload.min.js')}}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function() {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
    });

</script>

{% block js %}
{% endblock %}
</body>
</html>

app/templates/home/index.html
{% extends "home/home.html" %}

{% block content %}

<section id="movielist">
    <div class="container">
        <div class="row wow fadeIn" data-wow-delay="0.6s">
            {% for v in movie %}
            <div class="col-md-3">
                <div class="movielist text-center">
                    <img  src="{{url_for('static',filename='uploads/'+v.logo)}}"
                         class="img-responsive center-block" alt="" >
                    <div class="text-left" style="margin-left:auto;margin-right:auto;width:210px;">
                        <span style="color:#999;font-style: italic;">{{v.title}}</span><br>

                    </div>
                    <a href="{{ url_for('home.play',id=v.id)}}" class="btn btn-primary" target="_blank"
                       role="button"><span class="glyphicon glyphicon-play"></span>&nbsp;播放</a>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</section>

{% endblock %}

app/templates/home/layout.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{ url_for('static',filename = 'base/images/logo.png')}}">
    <link rel="stylesheet" href="{{ url_for('static',filename = 'base/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{ url_for('static',filename = 'base/css/bootstrap-movie.css')}}">
    <link rel="stylesheet" href="{{ url_for('static',filename = 'base/css/animate.css')}}">
    <style>
        .navbar-brand>img {
            display: inline;
        }
        .media{
            padding:3px;
            border:1px solid #ccc
        }

    </style>
    {% block css %} {%endblock%}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index')}}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static',filename = 'base/images/logo.png')}}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！">
                    <span class="input-group-btn">
                        <a class="btn btn-default" href="{{ url_for('home.search')}}"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{url_for('home.index')}}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.login')}}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.register')}}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.logout')}}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.user')}}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->


    {% block content %} {% endblock %}

<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2019 liuYuJiang
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static',filename = 'base/js/jquery.min.js')}}"></script>
<script src="{{ url_for('static',filename = 'base/js/bootstrap.min.js')}}"></script>
<script src="{{ url_for('static',filename = 'base/js/jquery.singlePageNav.min.js')}}"></script>
<script src="{{ url_for('static',filename = 'base/js/wow.min.js')}}"></script>
<script src="{{ url_for('static',filename = 'lazyload/jquery.lazyload.min.js')}}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function() {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
    });

</script>

{% block js %}
{% endblock %}
</body>
</html>

app/templates/home/logout.html
{% extends "home/home.html" %}

{% block content %}

<h1>hello logout !</h1>
{% endblock %}

app/templates/home/menu.html
    <div class="col-md-3">
        <div class="list-group">
            <a id="m-1" href="{{url_for('home.user')}}" class="list-group-item ">
                <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
            </a>
             <a id="m-2" href="{{url_for('home.pwd')}}" class="list-group-item">
                <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
            </a>
            <a id="m-3" href="{{url_for('home.comments',page=1)}}" class="list-group-item">
                <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
            </a>
        </div>
    </div>

app/templates/home/moviecol.html
{% extends "home/home.html" %}
{% block css %}
<style>
        .col-lg-1, .col-lg-10, .col-lg-11, .col-lg-12, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-md-1, .col-md-10, .col-md-11, .col-md-12, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-sm-1, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-xs-1, .col-xs-10, .col-xs-11, .col-xs-12, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9{
            padding-right: 3px;
            padding-left: 3px;
        }

</style>
{%endblock%}

{% block content %}
{% include "home/menu.html" %}
    <div class="col-md-9">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;收藏电影</h3>
            </div>
            <div class="panel-body">
                <div class="col-md-12">

                    {% for v in range(1,6) %}
                    <div class="media">
                        <div class="media-left">
                            <a href="{{ url_for('home.play',id=5)}}">
                                <img class="media-object" src="holder.js/131x83" alt="环太平洋">
                            </a>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading">环太平洋<a href="{{ url_for('home.play',id=5)}}" class="label label-primary pull-right"><span class="glyphicon glyphicon-play"></span>播放影片</a></h4>
                            该片主要讲述了人类为了抵抗怪兽的进攻，研制出了高大的机器战士与来犯怪兽进行对抗的故事。
                        </div>
                    </div>
                    {% endfor %}

                </div>
                <div class="col-md-12 text-center" style="margin-top:6px;">
                    <nav aria-label="Page navigation">
                        <ul class="pagination">
                            <li>
                                <a href="#" aria-label="First">
                                    <span aria-hidden="true">首页</span>
                                </a>
                            </li>
                            <li>
                                <a href="#" aria-label="Previous">
                                    <span aria-hidden="true">上一页</span>
                                </a>
                            </li>
                            <li><a href="#">1&nbsp;/&nbsp;10</a></li>
                            <li>
                                <a href="#" aria-label="Next">
                                    <span aria-hidden="true">下一页</span>
                                </a>
                            </li>
                            <li>
                                <a href="#" aria-label="Last">
                                    <span aria-hidden="true">尾页</span>
                                </a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}

<script >

    $(document).ready(function(){
        $("#m-5").addClass("active")
    })
</script>
{% endblock %}

app/templates/home/mycb.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>myvcb</p>


</body>
</html>

app/templates/home/search.html
{% extends "home/home.html" %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb" style="margin-top:6px;">
                <li>与"{{data}}"有关的电影，共{{moviecount}}部</li>
            </ol>
        </div>
        <div class="col-md-12">

            {% for v in moviex %}
            <div class="media">
                <div class="media-left">
                    <a href="{{ url_for('home.play',id=v.id)}}">
                        <img class="media-object" width="131px" height="83px" src="{{url_for('static',filename='uploads/'+v.logo)}}" alt="{{v.title}}">
                    </a>
                </div>
                <div class="media-body">
                    <h4 class="media-heading">{{v.title}}<a href="{{ url_for('home.play',id=v.id)}}" class="label label-primary pull-right"><span class="glyphicon glyphicon-play"></span>播放影片</a></h4>
                    {{v.info}}
                </div>
            </div>
            {% endfor %}

        </div>
        <div class="col-md-12 text-center">

        </div>
    </div>

{% endblock %}